name: Build and analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout layerGenerator
      uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java
    - name: Build and analyze layer generator sources
      env:
        GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -P sonar-cloud --file pom.xml
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    - name: delete old versions of layer-generator
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator
        ignore-versions: ^(?!.*?1\.2-SNAPSHOT).*
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-plugin
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-plugin
        ignore-versions: ^(?!.*?1\.2-SNAPSHOT).*
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-annotation
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-annotation
        ignore-versions: ^(?!.*?1\.2-SNAPSHOT).*
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-sources
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-sources
        ignore-versions: ^(?!.*?1\.2-SNAPSHOT).*
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-sample
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-sample
        ignore-versions: ^(?!.*?1\.2-SNAPSHOT).*
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: Deploy layer generator
      env:
        GITHUB_TOKEN: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
      run: mvn -B deploy --file pom.xml