name: Build and analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout layerGenerator
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt
        java-package: jdk
        cache: 'maven'
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
    - name: Build and analyze layer generator sources
      env:
        GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -P sonar-cloud --file pom.xml
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
    - name: delete old versions of layer-generator
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator
        ignore-versions: ^(?:\d+\.\d+(\.\d+)?)$
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-plugin
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-plugin
        ignore-versions: ^(?:\d+\.\d+(\.\d+)?)$
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-annotation
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-annotation
        ignore-versions: ^(?:\d+\.\d+(\.\d+)?)$
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-sources
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-sources
        ignore-versions: ^(?:\d+\.\d+(\.\d+)?)$
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: delete old versions of layer-generator-sample
      uses: actions/delete-package-versions@v2
      with:
        package-name: de.ma_vin.util.layer.generator.layer-generator-sample
        ignore-versions: ^(?:\d+\.\d+(\.\d+)?)$
        token: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
    - name: Deploy layer generator
      env:
        GITHUB_TOKEN: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
      run: mvn -B deploy --file pom.xml