# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout layerGenerator
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout ape
      uses: actions/checkout@v2
      with:
        repository: Ma-Vin/de.mv.ape
        token: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        path: ape
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build ape
      run: mvn -B clean install --file ape/pom.xml
    - name: Build layerGenerator
      run: mvn -B clean verify --file main/pom.xml
