name: Build and analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout layerGenerator
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout ape
      uses: actions/checkout@v2
      with:
        repository: Ma-Vin/de.ma_vin.ape
        token: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        path: ape
    - name: Checkout ape utils
      uses: actions/checkout@v2
      with:
        repository: Ma-Vin/de.ma_vin.ape.utils
        token: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        path: ape/apeutils
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build ape
      run: mvn -B clean install --file ape/pom.xml
    - name: Build apeutils
      run: mvn -B clean install --file ape/apeutils/pom.xml
    - name: Build and analyze layer generator sources
      env:
        GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -P sonar-cloud --file main/pom.xml