name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout layerGenerator
        uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package of layer generator
        env:
          GITHUB_TOKEN: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
        run: mvn -B deploy