name: deploy release

on:
  push:
    branches: [ 'release/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout layerGenerator
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
        java-package: jdk
        cache: 'maven'
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
    - name: Build and analyze layer generator sources
      env:
        GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -P sonar-cloud --file pom.xml
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout layerGenerator
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
        java-package: jdk
        cache: 'maven'
    - name: Deploy layer generator
      env:
        GITHUB_TOKEN: ${{ secrets.LAYER_GITHUB_PACKAGES_PAT }}
      run: mvn -B clean deploy --file pom.xml -DskipTests